name: b24_torque_monitor
description: B24 Torque monitoring application for pile installation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_blue_plus: ^1.32.11
  excel: ^4.0.6
  file_picker: ^8.0.0
  fl_chart: ^0.69.0
  path_provider: ^2.1.3
  csv: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true