name: b24_torque_monitor
description: B24 Torque Monitoring System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_blue_plus: ^1.31.15
  excel: ^4.0.2
  file_picker: ^8.0.0
  fl_chart: ^0.66.0
  path_provider: ^2.1.1
  csv: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true